# Generated by Django 4.2 on 2023-05-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_usershippinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=7, null=True)),
                ('order_status', models.IntegerField(choices=[(1, 'New'), (2, 'Processing'), (3, 'Ready to ship'), (4, 'Shipped'), (5, 'Delivered'), (6, 'Canceled')], default=1, verbose_name='Order status')),
                ('coupon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Coupon')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Total amount of order')),
                ('payment_method', models.IntegerField(choices=[(1, 'By cash'), (2, 'By card')], default=1)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comment')),
                ('shipping_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usershippinginfo', verbose_name='Shipping info')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['total_amount'],
            },
        ),
    ]
