# Generated by Django 4.2 on 2023-05-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='activate_bonuses',
            field=models.BooleanField(default=False, verbose_name='Activate bonuses'),
        ),
        migrations.AddField(
            model_name='order',
            name='create_account',
            field=models.BooleanField(default=False, verbose_name='Create an account'),
        ),
    ]
