# Generated by Django 4.2 on 2023-05-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_usercoupons_valid_to'),
        ('orders', '0015_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.usercoupons', verbose_name='Coupon'),
        ),
    ]
