# Generated by Django 4.2 on 2023-05-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=1, max_length=170, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=180, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='patronymic',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Patronymic'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_office',
            field=models.CharField(default=1, max_length=450, verbose_name='Post office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default=1, max_length=190, verbose_name='Surname'),
            preserve_default=False,
        ),
    ]
