# Generated by Django 4.2 on 2023-05-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_bonuses_amount',
            field=models.IntegerField(default=0, verbose_name='Total amount of bonuses for order'),
        ),
    ]
