# Generated by Django 4.2 on 2023-05-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_products_availability_status'),
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_item', models.IntegerField(default=0, verbose_name='Price per item')),
                ('product_article', models.CharField(blank=True, max_length=8, null=True, verbose_name='Product article')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Quantity in stock')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Quantity sold')),
                ('stock_date', models.DateTimeField(blank=True, null=True, verbose_name='Stock date')),
                ('last_sales_date', models.DateTimeField(blank=True, null=True, verbose_name='Last sales date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_info', to='products.products', verbose_name='Product')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Product category')),
            ],
            options={
                'verbose_name': 'stock item',
                'verbose_name_plural': 'Stock items',
            },
        ),
    ]
