# Generated by Django 4.2 on 2023-04-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_variationcategory_value_alter_variationcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Article'),
        ),
    ]
