# Generated by Django 4.2 on 2023-04-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentOfVariationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'variation parent category',
                'verbose_name_plural': 'Parents of variations categories',
            },
        ),
        migrations.AddField(
            model_name='variationcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_variation_category', to='products.parentofvariationcategory', verbose_name='Parent'),
        ),
    ]
