# Generated by Django 4.2 on 2023-04-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_parentofvariationcategory_variationcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_variation_categories', to='products.parentofvariationcategory', verbose_name='Parent'),
        ),
    ]
