# Generated by Django 4.2 on 2023-04-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_variationcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentofvariationcategory',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=False),
        ),
    ]
