# Generated by Django 4.2 on 2023-04-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_parentofvariationcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentofvariationcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
