# Generated by Django 4.2 on 2023-04-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_parentofvariationcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentofvariationcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
