# Generated by Django 4.2 on 2023-05-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bonuses',
            field=models.IntegerField(default=0, verbose_name='Bonuses(Optional)'),
        ),
    ]
