# Generated by Django 4.2 on 2023-05-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_products_bonuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(blank=True, max_length=16, null=True, verbose_name='Coupon')),
                ('discount', models.PositiveSmallIntegerField(default=1, verbose_name='Discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='products.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['discount'],
            },
        ),
    ]
