# Generated by Django 4.2 on 2023-05-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='drop_chance',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Chance to drop'),
        ),
    ]
