# Generated by Django 4.2 on 2023-05-15 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0002_coupons_drop_chance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(auto_now_add=True, verbose_name='Coupon start date')),
                ('valid_to', models.DateField(blank=True, verbose_name='Coupon valid to')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupons', verbose_name='Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'user coupon',
                'verbose_name_plural': "Users' coupons",
            },
        ),
    ]
