# Generated by Django 4.2 on 2023-05-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usershippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershippinginfo',
            name='city',
            field=models.CharField(default=1, max_length=170, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usershippinginfo',
            name='country',
            field=models.CharField(default=1, max_length=150, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
