# Generated by Django 4.2 on 2023-05-05 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_usershippinginfo_session_id'),
        ('orders', '0009_remove_order_address_remove_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.IntegerField(choices=[(1, 'By cash'), (2, 'By card')], verbose_name='Payment method')),
                ('payment_amount', models.IntegerField(default=0, verbose_name='Payment amount')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Order is paid')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='orders.order', verbose_name='Order')),
                ('shipping_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usershippinginfo', verbose_name='User shipping info')),
            ],
            options={
                'verbose_name': 'payment info',
                'verbose_name_plural': 'Payment infos',
            },
        ),
    ]
