# Generated by Django 4.2 on 2023-04-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variationcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationcategory',
            name='value',
            field=models.CharField(default=1, max_length=200, verbose_name='Value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variationcategory',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Variation category name'),
        ),
        migrations.CreateModel(
            name='ProductVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.products', verbose_name='Product')),
                ('variation_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variationcategory', verbose_name='Variation category')),
            ],
            options={
                'verbose_name': 'variation',
                'verbose_name_plural': 'Product variations',
                'unique_together': {('product', 'variation_category')},
            },
        ),
    ]
