# Generated by Django 4.2 on 2023-05-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_parentofvariationcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='availability_status',
            field=models.IntegerField(choices=[(1, 'in stock'), (2, 'awaiting arrival'), (3, 'low in stock'), (4, 'out of stock')], default=1),
        ),
    ]
