# Generated by Django 4.2 on 2023-05-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='bonus_taken',
            field=models.BooleanField(default=False, verbose_name='Bonus taken'),
        ),
    ]
