# Generated by Django 4.2 on 2023-05-04 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=180, verbose_name='Name')),
                ('surname', models.CharField(max_length=190, verbose_name='Surname')),
                ('patronymic', models.CharField(blank=True, max_length=180, null=True, verbose_name='Patronymic')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('post_office', models.CharField(max_length=450, verbose_name='Post office')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'shipping info',
                'verbose_name_plural': 'Shipping Infos',
            },
        ),
    ]
