# Generated by Django 4.2 on 2023-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_usershippinginfo_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershippinginfo',
            name='session_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
