# Generated by Django 4.2 on 2023-05-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usershippinginfo_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippinginfo',
            name='session_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
